apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seokpan-app
resources:
  - ../../../base/backend
  - routes.yaml
images:
  - name: harbor.seokpan.soldesk.store/seokpan/backend
    newName: image-registry.openshift-image-registry.svc:5000/seokpan-app/backend
    digest: sha256:994307ad5ffc323e83772465645739058a68bfe7d74b59c817e12f2ebee18f50
replicas:
  - name: backend
    count: 1
patches:
  - target: {kind: ConfigMap, name: backend-config}
    path: patch-config.yaml
  - target: {kind: PodDisruptionBudget, name: backend}
    patch: |-
      $patch: delete
      apiVersion: policy/v1
      kind: PodDisruptionBudget
      metadata:
        name: backend
  - target: {kind: Deployment, name: backend}
    patch: |-
      - op: remove
        path: /spec/template/spec/imagePullSecrets
  - target: {kind: ConfigMap, name: seokpan-internal-ca}
    path: patch-ca.yaml
  - target: {kind: Deployment, name: backend}
    path: patch-hostaliases.yaml
