apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
spec:
  host: seokpan-lab.apps.demo2.ocp4lab.com
  to: {kind: Service, name: frontend}
  port: {targetPort: http}
  tls: {termination: edge, insecureEdgeTerminationPolicy: Redirect}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: backend-api
spec:
  host: seokpan-lab.apps.demo2.ocp4lab.com
  path: /api/v1
  to: {kind: Service, name: backend}
  port: {targetPort: http}
  tls: {termination: edge, insecureEdgeTerminationPolicy: Redirect}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: backend-ws
  annotations:
    haproxy.router.openshift.io/timeout-tunnel: 1h
spec:
  host: seokpan-lab.apps.demo2.ocp4lab.com
  path: /ws/v1
  to: {kind: Service, name: backend}
  port: {targetPort: http}
  tls: {termination: edge, insecureEdgeTerminationPolicy: Redirect}
