apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: backend
spec:
  type: ClusterIP
  selector: {app.kubernetes.io/name: backend}
  ports:
    - {name: http, port: 8000, targetPort: http, protocol: TCP}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
spec:
  type: ClusterIP
  selector: {app.kubernetes.io/name: frontend}
  ports:
    - {name: http, port: 8080, targetPort: http, protocol: TCP}
