# Owner: 정태훈
# Scope: Application Runtime / GitOps
# Related: seokpan-gitops#35, seokpan-app#50
# Public Root CA certificate only. Never add the CA private key or service private keys here.

apiVersion: v1
kind: ConfigMap
metadata:
  name: seokpan-internal-ca
  namespace: application
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFdTCCA12gAwIBAgIUYlBzcL55hISQHf65kjQcqX6llbUwDQYJKoZIhvcNAQEL
    BQAwQjELMAkGA1UEBhMCS1IxEDAOBgNVBAoMB3Nlb2twYW4xITAfBgNVBAMMGFNl
    b2twYW4gSW50ZXJuYWwgUm9vdCBDQTAeFw0yNjA5MDkwODAzMzBaFw0zNjA5MDYw
    ODAzMzBaMEIxCzAJBgNVBAYTAktSMRAwDgYDVQQKDAdzZW9rcGFuMSEwHwYDVQQD
    DBhTZW9rcGFuIEludGVybmFsIFJvb3QgQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4IC
    DwAwggIKAoICAQCsnDfaJNwq/DvSG/o1D/8vO+f7bDtwC5Se1Kh1Hzz85gSdNxoV
    JPLu3AVF0LVZIpd7VimmWnQzlPd/Jb35z9rDkbvM9/58DeJ2VGJ8jV7zVLU6/qCS
    w+cMWGN1Hf1Xpht+wq+liuZRY9wqPDwh3A7rURhVvsYnZFFXbMqDea8oXdVL9+Ox
    OzWv28bAn7wOGpGDdhjthoEUYJ+iwhpD3DgHOzR1MXAhZCsDr9+FGNU5XEmRshds
    ZhsmKGbfGP7SUsfjSYrHaFj3KsCB5beq3DhaPtJfq/9fJwJi3SEGtqfhRkYqyWq3
    lRVTCrjW3e3IvOqP2lWOp8JMHP7TDZRonTafOUMVNAL/XM1x9H4hy++9aVR38yLd
    gPtdCGMg3UTP4f77T15pfXbE7RtLNRV2QqJ07qAe12mOjGmV6kzOcZ+y6h8FS9hU
    mR/zMoNCop4ty4qyTkT9n7r/ttnnJi4YevbdUEC/gjOddpHowQ+wbDgyoccnqseb
    lcC5N8zpjKkpu7I2CN4R0fKQkeid9E8inGYPvbiH0um/+jdGLJJHcKYSUTCJXm/s
    SKvY36wMLns6JE3yI3JZgE/26aADNHpS7ydnwkeHMYk7f+12n3NC5J5D046bAnTn
    TdS9Qc3jf5SjFtzYu6jkgTbYu7fZe6S/j8/TC9/HLzLzOGvQn77xHu6i0wIDAQAB
    o2MwYTAdBgNVHQ4EFgQUWhJop2U6v9I4gWKhdQyKlQZuv50wHwYDVR0jBBgwFoAU
    WhJop2U6v9I4gWKhdQyKlQZuv50wDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8E
    BAMCAQYwDQYJKoZIhvcNAQELBQADggIBAGZYUXRpn2WErtV7JW+p32bL2RWl6E3u
    13VNj7qtIswFfNxG38Ez2rWS7Lty4O8d9wHS37gu1wz0VUwe1Tv2Xbt6TQL6j/wi
    L2o9aLaaioDGXwHI9NupTIqM8Xxuik8UQwvNqXRkCO2mDBgVG3YT9hukd+mwgtxA
    d9CjBBMSkaeixlB2pMijyTVTrOnFGdS72QsFWmH/CXnk5TLk9ifBK5ZaonFbuqOE
    b8CP3HKCDMIf4l0BpgQp7k2qnb6XrqVbGjz96qgK4dps+KfHoNmEkpAK3JBfm8aQ
    BeDKX69XWMyCCQkzCKUgLE4OUp7E72HPP7i9TiJXbZt+XOdXwQzkppULzVmoDNPO
    u8eLXwssIIKBMR3HKhFX7luWCLdYSi2mnv1GF0SDsE6CaN7EVDi8BpQEcHKnT2bl
    WNiBQhLSjcuvMMMgarREsjFfhKEoftWI5O35l05y8rkGpiMVjqYbEG3dqsmwrKiR
    4smIHmsiZjlklh6Oy9oLjAwZ/wBgmPiDV7DeSQ+7y7mB030vdHaFwlSUDds9N3mv
    jTBlsdoVX+8BMmOjLODYmwEJ4a5xSp9UgivWu2b6ykB0GwR7QUUw5Gq8eCtGHHKy
    3MhkLX3XDy7HbEFkls8sV1S/1d32QMXn/PmJIKLeX+gp5JdihJur+5T/5c89XlMK
    0AN8N9Zf0B6l
    -----END CERTIFICATE-----
